# Generated by Django 2.2.4 on 2020-03-25 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
