# Generated by Django 2.1.1 on 2018-10-09 19:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('art_description', models.CharField(max_length=250)),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('price_artwork_per_day', models.FloatField()),
                ('likes', models.IntegerField(default=0)),
                ('artwork_image', models.FileField(default='static/homepage/artwork_images/no-img.jpeg', upload_to='artwork_images/%Y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('art_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Date', models.DateField(default=datetime.date.today)),
                ('To_Date', models.DateField()),
                ('total_price', models.FloatField(default=0.0)),
                ('artwork_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_description', models.CharField(max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='business_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Business'),
        ),
    ]
