# Generated by Django 2.2.4 on 2020-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200325_1954'),
        ('user', '0005_remove_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('artist', models.BooleanField(choices=[('Yes', True), ('No', True)], default=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['c_time'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
