# Generated by Django 2.2.4 on 2020-03-26 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200325_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='verifyCode')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'retrieve')], max_length=10, verbose_name='verifyCodeType')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2020, 3, 26, 12, 52, 27, 575390), verbose_name='sendTime')),
            ],
            options={
                'verbose_name': 'Email verification code',
                'verbose_name_plural': 'Email verification code',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='artist',
            field=models.BooleanField(choices=[('Yes', True), ('No', False)], default=True),
        ),
    ]
