# Generated by Django 2.2.4 on 2020-03-26 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200326_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 15, 32, 17, 857549), verbose_name='sendTime'),
        ),
    ]
