# Generated by Django 2.2.4 on 2020-04-02 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200402_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 21, 21, 35, 688255), verbose_name='sendTime'),
        ),
    ]
