# Generated by Django 2.2.4 on 2020-04-02 10:34

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200402_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='country',
            field=django_countries.fields.CountryField(default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 21, 34, 14, 554961), verbose_name='sendTime'),
        ),
    ]
