# Generated by Django 2.2.4 on 2020-04-21 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200402_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'ordering': ['id'], 'verbose_name': 'AdditionalInfo', 'verbose_name_plural': 'AdditionalInfo'},
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 11, 11, 43, 324711), verbose_name='sendTime'),
        ),
    ]
