# Generated by Django 2.2.4 on 2020-04-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_auto_20200421_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='Img')),
                ('thumbnail', models.ImageField(upload_to='Thumbnail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User')),
            ],
            options={
                'verbose_name': 'artwork',
                'verbose_name_plural': 'artworks',
                'ordering': ['id'],
            },
        ),
    ]
